### PR TITLE
adapt fuse.py to Glyphs

### PR DESCRIPTION
**Pull request by schriftgestalt**
I needs the latest version of objectsGS.py from https://github.com/schriftgestalt/Glyphs-Scripts

### CODE REVIEW

**Comment by benkiel** [comment]
I'm going to merge this, but need to test the new dialog code in RoboFont. Also, I'm going to not have the positions cast as ints. That's something for an editor to control, not this script. If you want your editor to have fractional glyph widths and/or fractional component positions, this shouldn't interfere. 

Thanks for the catch on the other things and the checking of it in Glyphs!

**Comment by schriftgestalt** [comment]
> If you want your editor to have fractional glyph widths and/or fractional component positions, this shouldn't interfere.

ok. But then you need to change the import code to not expect ints, too. That was just my solution for get the import to work.

**Comment by schriftgestalt** [comment]
And it might be a good idea to add the UserDefaults to RoboFab?

**Comment by benkiel** [comment]
Right you on on the import. I'll see about UserDefaults for RoboFab. There's only so much time/life that these scripts deserve, they're ten years old and posted at John's nudging...

**Comment by benkiel** [comment]
Right you are on the import. I'll look at user defaults for RoboFab, but there is only so much time that it makes sense to spend on these scripts.

**Comment by schriftgestalt** [comment]
I was using it as a test case for my robofab implementation and it showed my some problems. So it was time well spent.

**Pull request merged**
